#!/usr/bin/env bash
book_path=${1:-"./alice_in_wonderland.txt"}
scripts_dir=$(dirname "$(readlink -f "$0")")

if test -z "$book_path"; then
   echo "Usage: $0 <path-to-book>"
   exit 1
fi

if ! test -f "$book_path"; then
   echo "file doesn't exist at given path '$book_path'"
   exit 1
fi

function get_stats() {
   path=${1:-""}

   title="Statistics for '$(basename "$path")'"
   underline=$(head -c ${#title} < /dev/zero | tr '\0' '#')
   printf "\n%s\n%s\n" "$title" "$underline"

   "$scripts_dir"/more_than_average "$path"
   "$scripts_dir"/next_most_frequent "$path"
   "$scripts_dir"/most_common_word "$path"
}

# transform path to absolute
abs_path=$(readlink -f "$book_path")
chapters_dir=$("$scripts_dir"/generate_chapters "$abs_path")

for chapter in "$chapters_dir"/*.txt; do
   get_stats "$chapter"
done

get_stats "$abs_path"
